sudo: required
services:
  - docker

before_install:
  - docker build -t mbrandt5874/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mbrandt5874/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-225488278550"
  bucket_path: "docker-react"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
